
name: CI

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job_one:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: |  
          echo Job 1 will started:
          for i in {1..10}; do echo $i; sleep 2; done # Simulate "long process"
          echo "Job 1 was completed"
