# More info on https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
name: CI Display message with manual trigger

on: # Controls when the workflow will run

  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
   inputs:
      message:
        description: 'Message to display'
        required: true
        default: 'Hi' # Default value
      otherMessage:
        description: 'Test scenario tags'  

jobs: # A workflow run is made up of one or more jobs that can run sequentially or in parallel
  show_message: # This workflow contains a single job called "Show_message"
    runs-on: ubuntu-latest # The type of runner that the job will run on
    steps:
      - name: Run echo messages # Runs a single command using the runners shell
        run: |
          echo "First message: ${{ github.event.inputs.message }}"
          echo "Other message: ${{ github.event.inputs.otherMessage }}" 
